#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biometria_Projekt
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Keystroke")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Biometria_Projekt.Properties.Settings.Default.KeystrokeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table2> Table2s
		{
			get
			{
				return this.GetTable<Table2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table2")]
	public partial class Table2
	{
		
		private string _time;
		
		private System.Nullable<int> _user_id;
		
		private string _input0;
		
		private string _input1;
		
		private string _inputMouse;
		
		private string _IP;
		
		private string _browser;
		
		public Table2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_input0", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string input0
		{
			get
			{
				return this._input0;
			}
			set
			{
				if ((this._input0 != value))
				{
					this._input0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_input1", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string input1
		{
			get
			{
				return this._input1;
			}
			set
			{
				if ((this._input1 != value))
				{
					this._input1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inputMouse", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string inputMouse
		{
			get
			{
				return this._inputMouse;
			}
			set
			{
				if ((this._inputMouse != value))
				{
					this._inputMouse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this._IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_browser", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string browser
		{
			get
			{
				return this._browser;
			}
			set
			{
				if ((this._browser != value))
				{
					this._browser = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
